class Strategy:
    """
    Strategy is an abstract base class providing an interface for
    all subsequent (inherited) strategy handling objects.

    The goal of a (derived) Strategy object is to generate Signal
    objects for particular symbols based on the inputs of Bars
    (OLHCVI) generated by a DataHandler object.

    This is designed to work with both historic and live data as
    the Strategy object is agnostic to the data source.
    """

    def calculate_signals(self, event):
        """
        Provides the mechanisms to calculate the list of signals.
        This method is implemented by all inheriting classes.
        """
        raise NotImplementedError("Should implement calculate_signals()")
